### ISSUE TITLE
Error when loading page

### ISSUE THREAD

**Issue by namelessperson0** [jsonpreet/videso#1]
After I go to https://www.videso.xyz I get the logo and nothing happens.
There are 2 errors in browser console with respect to manifest.json
Check below screenshot.
![image](https://user-images.githubusercontent.com/72940077/219016069-f74e6710-d5f4-4e84-b65d-06ff56e33775.png)

**Comment by jsonpreet** [comment]
Hi Sir, It's because I am working on ViDeso 2.0 Will be back soon.
